name: test

on:
  push:
    branches: [main]

jobs:
  fractal_build:
    name: Fractal Build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          npm install
          npm run fractalBuild
