name: test

on:
  push:
    branches: [main]

jobs:
  fractal_build:
    name: Fractal Build
    runs-on: ubuntu-latest
    # runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest]
    #     node-version: [12.x, 14.x]
    # steps:
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #   - name: npm install, and test
    #     run: npm install
    #     # with:
    #     #   path: ../

    #     # run: |
    #     #   npm install
    #     #   npm test
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        # working-directory: ../test
        run: npm install
      - name: scssBuild
        run: gulp scssBuild
      - name: fractalInstall
        run: npm install -g @frctl/fractal
      - name: build2
        run: fractal build
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./
      # run: |
      #   npm install
      #   fractal build
